apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: {{ .Release.Name }}-db
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.postgres.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_DB: {{ .Values.secrets.postgres.POSTGRES_DB | b64enc }}
